<script setup>
import { storeToRefs } from "pinia";
import { getDisplayName, isAutogeneratedNickname } from "@/utils/user";

// Feature flag — Speed Wash al lanzamiento solo vende packs (no billetera
// con saldo). Si en el futuro se habilita, flipear a true y el bloque vuelve.
const SHOW_WALLET = false;

const { t } = useI18n();
const router = useRouter();
const userStore = useUserStore();
const { isGuest } = storeToRefs(userStore);
const userInfo = ref(null);

// Solo traemos el perfil para usuarios con cuenta real. Un invitado no tiene
// token, así que myInfo() no devuelve nada útil: en su lugar mostramos el
// estado "invitado" con CTA para crear cuenta.
if (!isGuest.value) {
  const { data } = myPageApi.myInfo();
  watchEffect(() => {
    if (data.value) userInfo.value = data.value;
  });
}

// Nombre a mostrar en el header. Si el backend nos dio un nickname real
// (el usuario lo editó), lo usamos tal cual: "Federico". Si es el código
// autogenerado tipo "b9xN3842" o está vacío, mostramos "Hola, ···1234" para
// que se sienta reconocido sin mostrar un string sin sentido. Ver
// utils/user.js y CHANGELOG.md sección 2.4.
const hasRealName = computed(() => {
  const nick = userInfo.value?.nickName?.trim();
  return !!nick && !isAutogeneratedNickname(nick);
});
const displayName = computed(() =>
  getDisplayName(userInfo.value) || t("routes.mine.defaultUser")
);
const headerName = computed(() =>
  hasRealName.value
    ? displayName.value
    : t("routes.mine.greeting", { name: displayName.value })
);

// Contador de cada acceso directo a pedidos. Mismo criterio que myInfo: solo
// lo pedimos con cuenta real. Un invitado no tiene token y washOrderPage le
// devolvería 999, que en una página protegida como esta lo patea a /login
// (ver useApi.js) — o sea que abrir Mi cuenta lo expulsaría.
// Los valores son los del filtro `state`: 2 en curso, 3 a pagar, 4 completados.
const ORDER_SHORTCUTS = [2, 3, 4];
const { getOrderCounts } = useOrder();
const orderCounts = ref(
  ORDER_SHORTCUTS.reduce((acc, state) => ({ ...acc, [state]: null }), {})
);

if (!isGuest.value) {
  onMounted(async () => {
    orderCounts.value = await getOrderCounts(ORDER_SHORTCUTS);
  });
}

// Cerrar sesión — mismo flujo que en Configuración.
const handleLogout = () => {
  showDialog({
    title: t("routes.settings.logout.title"),
    message: t("routes.settings.logout.message"),
    showCancelButton: true,
  }).then(() => {
    userStore.logout();
    router.push("/login");
  });
};
</script>

<template>
  <div class="mine-page">
    <!-- Estado invitado: sin cuenta real, empujamos a crear cuenta -->
    <template v-if="isGuest">
      <div class="mine-header">
        <div class="mine-header__bg"></div>
        <div class="mine-header__content">
          <div class="mine-avatar">
            <van-icon name="user-o" size="28" color="#00BBFC" />
          </div>
          <div class="mine-user-info">
            <h2 class="mine-user-name">{{ t('routes.mine.guest.name') }}</h2>
          </div>
        </div>
      </div>

      <div class="mine-section">
        <div class="guest-card">
          <h3 class="guest-card__title">{{ t('routes.mine.guest.title') }}</h3>
          <p class="guest-card__sub">{{ t('routes.mine.guest.subtitle') }}</p>
          <van-button block round type="primary" class="guest-card__primary" @click="router.push('/register')">
            {{ t('routes.mine.guest.createAccount') }}
          </van-button>
          <van-button block round class="guest-card__ghost" @click="router.push('/login')">
            {{ t('routes.mine.guest.login') }}
          </van-button>
        </div>
      </div>
    </template>

    <!-- Perfil de usuario con cuenta real -->
    <template v-else>
    <!-- Header con avatar -->
    <div class="mine-header">
      <div class="mine-header__bg"></div>
      <div class="mine-header__content">
        <div class="mine-avatar">
          <van-icon name="user-o" size="28" color="#00BBFC" />
        </div>
        <div class="mine-user-info">
          <router-link to="/settings/nickname" class="mine-user-name-row">
            <h2 class="mine-user-name">{{ headerName }}</h2>
            <van-icon name="edit" size="14" color="rgba(255,255,255,0.5)" />
          </router-link>
          <p class="mine-user-phone">{{ userInfo?.phoneNum || '' }}</p>
        </div>
        <router-link to="/settings" class="mine-settings-btn">
          <van-icon name="setting-o" size="22" color="rgba(255,255,255,0.7)" />
        </router-link>
      </div>
    </div>

    <!-- Saldo — oculto por SHOW_WALLET flag. Speed Wash solo vende packs. -->
    <div v-if="SHOW_WALLET" class="mine-section" style="margin-top: -20px; position: relative; z-index: 2;">
      <div class="balance-card" @click="$router.push('/wallet')">
        <div class="balance-card__left">
          <span class="balance-card__label">{{ t('routes.mine.wallet.balance') }}</span>
          <div class="balance-card__amount">
            <span class="balance-card__currency">$</span>
            <price-tag :price="userInfo?.balance" :show-currency="false" />
          </div>
        </div>
        <div class="balance-card__action">
          {{ t('routes.mine.wallet.viewAll') }}
          <van-icon name="arrow" size="14" />
        </div>
      </div>
    </div>

    <!-- Pedidos -->
    <div class="mine-section">
      <div class="section-header">
        <h3 class="section-title">{{ t('routes.mine.orders.title') }}</h3>
        <router-link to="/orders" class="section-link">
          {{ t('routes.mine.orders.viewAll') }}
          <van-icon name="arrow" size="12" />
        </router-link>
      </div>
      <div class="orders-grid">
        <router-link to="/orders?status=2" class="order-item">
          <div class="order-item__icon order-item__icon--progress">
            <van-icon name="clock-o" size="22" color="#00BBFC" />
            <span v-if="orderCounts[2]" class="order-item__badge">{{ orderCounts[2] }}</span>
          </div>
          <span class="order-item__text">{{ t('routes.mine.orders.status.inProgress') }}</span>
        </router-link>
        <router-link to="/orders?status=3" class="order-item">
          <div class="order-item__icon order-item__icon--pending">
            <van-icon name="balance-o" size="22" color="#FF9416" />
            <span v-if="orderCounts[3]" class="order-item__badge">{{ orderCounts[3] }}</span>
          </div>
          <span class="order-item__text">{{ t('routes.mine.orders.status.pending') }}</span>
        </router-link>
        <router-link to="/orders?status=4" class="order-item">
          <div class="order-item__icon order-item__icon--completed">
            <van-icon name="passed" size="22" color="var(--brand-success)" />
            <span v-if="orderCounts[4]" class="order-item__badge">{{ orderCounts[4] }}</span>
          </div>
          <span class="order-item__text">{{ t('routes.mine.orders.status.completed') }}</span>
        </router-link>
      </div>
    </div>

    <!-- Servicios -->
    <div class="mine-section">
      <div class="section-header">
        <h3 class="section-title">{{ t('routes.mine.services.title') }}</h3>
      </div>
      <router-link to="/vouchers" class="service-item">
        <div class="service-item__icon">
          <van-icon name="vip-card-o" size="22" color="#FF9416" />
        </div>
        <span class="service-item__text">{{ t('routes.mine.services.vipCard') }}</span>
        <van-icon name="arrow" size="14" color="#C0C4C8" />
      </router-link>
    </div>

    <!-- Cerrar sesión -->
    <div class="mine-section mine-logout">
      <van-button block round class="logout-btn" @click="handleLogout">
        {{ t('routes.settings.logout.button') }}
      </van-button>
    </div>
    </template>
  </div>
</template>

<style scoped>
.mine-page {
  min-height: 100vh;
  background: var(--background-color);
}

/* Header */
.mine-header {
  position: relative;
  padding: 24px 20px 40px;
  overflow: hidden;
}

.mine-header__bg {
  position: absolute;
  inset: 0;
  background:
    radial-gradient(120% 90% at 100% 0%, rgba(0, 187, 252, 0.16) 0%, transparent 55%),
    linear-gradient(160deg, #0B0B0D 0%, #000000 100%);
}

.mine-header__content {
  position: relative;
  z-index: 1;
  display: flex;
  align-items: center;
  gap: 14px;
}

.mine-avatar {
  width: 56px;
  height: 56px;
  border-radius: 50%;
  background: rgba(255, 255, 255, 0.12);
  border: 2px solid rgba(0, 187, 252, 0.3);
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
}

.mine-user-info {
  flex: 1;
  min-width: 0;
}

.mine-user-name-row {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  text-decoration: none;
  margin-bottom: 2px;
}

.mine-user-name {
  font-size: 18px;
  font-weight: 700;
  color: #fff;
  margin: 0;
}

.mine-user-phone {
  font-size: 13px;
  color: rgba(255, 255, 255, 0.5);
  margin: 0;
}

.mine-settings-btn {
  width: 40px;
  height: 40px;
  display: flex;
  align-items: center;
  justify-content: center;
  text-decoration: none;
}

/* Sections */
.mine-section {
  padding: 0 16px;
  margin-bottom: 16px;
}

/* Balance Card */
.balance-card {
  background: var(--surface-color);
  border: 1px solid var(--line-color);
  border-radius: 16px;
  padding: 20px;
  display: flex;
  align-items: center;
  justify-content: space-between;
  box-shadow: 0 12px 30px -18px rgba(0, 0, 0, 0.85);
  cursor: pointer;
  transition: transform 0.2s;
}

.balance-card:active {
  transform: scale(0.98);
}

.balance-card__label {
  font-size: 12px;
  color: var(--text-secondary);
  display: block;
  margin-bottom: 4px;
}

.balance-card__amount {
  display: flex;
  align-items: baseline;
  font-size: 32px;
  font-weight: 800;
  color: var(--text-primary);
}

.balance-card__currency {
  font-size: 18px;
  font-weight: 600;
  margin-right: 2px;
  color: var(--text-secondary);
}

.balance-card__action {
  display: flex;
  align-items: center;
  gap: 4px;
  font-size: 13px;
  font-weight: 500;
  color: #00BBFC;
}

/* Section Header */
.section-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 12px;
}

.section-title {
  font-size: 16px;
  font-weight: 700;
  color: var(--text-primary);
  margin: 0;
}

.section-link {
  display: flex;
  align-items: center;
  gap: 2px;
  font-size: 13px;
  color: #00BBFC;
  text-decoration: none;
  font-weight: 500;
}

/* Orders Grid */
.orders-grid {
  background: var(--surface-color);
  border: 1px solid var(--line-color);
  border-radius: 16px;
  padding: 16px 8px;
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 8px;
  box-shadow: 0 8px 24px -16px rgba(0, 0, 0, 0.8);
}

.order-item {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 8px;
  text-decoration: none;
  padding: 8px 0;
  transition: transform 0.2s;
}

.order-item:active {
  transform: scale(0.95);
}

.order-item__icon {
  position: relative;
  width: 44px;
  height: 44px;
  border-radius: 12px;
  display: flex;
  align-items: center;
  justify-content: center;
}

/* Globito con la cantidad, pegado al borde del icono. Solo aparece si hay
   al menos uno: un "0" flotando no aporta y ensucia la grilla. */
.order-item__badge {
  position: absolute;
  top: -6px;
  right: -6px;
  min-width: 18px;
  height: 18px;
  padding: 0 5px;
  border-radius: 9px;
  background: var(--primary-color);
  border: 2px solid var(--surface-color);
  color: #000;
  font-size: 11px;
  font-weight: 700;
  line-height: 14px;
  text-align: center;
  box-sizing: border-box;
}

.order-item__icon--progress { background: rgba(0, 187, 252, 0.14); }
.order-item__icon--pending { background: rgba(255, 148, 22, 0.14); }
.order-item__icon--completed { background: rgba(46, 204, 113, 0.14); }
.order-item__text {
  font-size: 12px;
  color: var(--text-primary);
  font-weight: 500;
}

/* Service Item */
.service-item {
  background: var(--surface-color);
  border: 1px solid var(--line-color);
  border-radius: 16px;
  padding: 16px 18px;
  display: flex;
  align-items: center;
  gap: 12px;
  text-decoration: none;
  box-shadow: 0 8px 24px -16px rgba(0, 0, 0, 0.8);
  transition: transform 0.2s;
}

.service-item:active {
  transform: scale(0.98);
}

.service-item__icon {
  width: 40px;
  height: 40px;
  border-radius: 10px;
  background: rgba(255, 148, 22, 0.14);
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
}

.service-item__text {
  flex: 1;
  font-size: 15px;
  font-weight: 600;
  color: var(--text-primary);
}

/* Estado invitado */
.guest-card {
  margin-top: -20px;
  position: relative;
  z-index: 2;
  background:
    radial-gradient(130% 120% at 100% 0%, rgba(0, 187, 252, 0.12) 0%, transparent 55%),
    var(--surface-color);
  border: 1px solid rgba(0, 187, 252, 0.3);
  border-radius: 18px;
  padding: 22px 18px;
  box-shadow: 0 12px 30px -18px rgba(0, 0, 0, 0.85);
  text-align: center;
}

.guest-card__title {
  font-family: var(--font-display);
  font-size: 18px;
  font-weight: 700;
  color: var(--text-primary);
  margin: 0 0 8px;
}

.guest-card__sub {
  font-size: 13px;
  line-height: 1.5;
  color: var(--text-secondary);
  margin: 0 0 18px;
}

.guest-card__primary {
  font-weight: 700;
  margin-bottom: 10px;
}

.guest-card__ghost {
  background: rgba(0, 187, 252, 0.08);
  border: 1px solid rgba(0, 187, 252, 0.45);
  color: #00BBFC;
  font-weight: 600;
}

/* Cerrar sesión — aire extra abajo para no quedar pegado al tabbar */
.mine-logout {
  margin-top: 24px;
  padding-bottom: calc(var(--van-tabbar-height) + env(safe-area-inset-bottom) + 24px);
}

.logout-btn {
  background: var(--surface-color);
  border: 1px solid var(--line-color);
  color: var(--brand-error);
  font-weight: 600;
}
</style>
