// Helpers de display para info del usuario.
// El backend autogenera `nickName` como un código tipo `b9xN3842` cuando el
// usuario se registra (documentado en CHANGELOG.md sección 2.4 — pendiente
// que el proveedor lo cambie). Mostrar ese código como si fuera el nombre
// del usuario queda feo y no comunica identidad. Estos helpers detectan el
// patrón y caen a un fallback amable basado en el teléfono.

// Patrón del nickname autogenerado por el backend: exactamente 8 caracteres
// alfanuméricos con mezcla de mayúsculas, minúsculas y números (ej: "b9xN3842").
// Un nombre real ("Federico"), un alias elegido ("fede123") o cualquier cosa
// que el usuario haya escrito NO cumple estas 3 condiciones a la vez.
const AUTOGEN_NICKNAME_REGEX = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[A-Za-z0-9]{8}$/;

export function isAutogeneratedNickname(nick) {
  if (!nick || typeof nick !== "string") return false;
  return AUTOGEN_NICKNAME_REGEX.test(nick);
}

// "···3197" — patrón banco, ofusca el teléfono pero deja los últimos 4 para
// que el usuario se reconozca sin exponer PII a alguien que espíe la pantalla.
export function maskPhone(phone) {
  const digits = String(phone || "").replace(/\D/g, "");
  if (!digits) return "";
  return `···${digits.slice(-4)}`;
}

// Nombre para mostrar en la app:
//  - Si el `nickName` es real (usuario lo editó) → devolvemos ese nombre.
//  - Si es autogenerado o vacío → caemos a "···1234" (últimos 4 del teléfono).
//  - Si no hay ni nickname ni teléfono → string vacía (el caller decide qué
//    mostrar por default, p.ej. "Usuario").
export function getDisplayName(userInfo) {
  const nick = userInfo?.nickName?.trim();
  if (nick && !isAutogeneratedNickname(nick)) return nick;
  return maskPhone(userInfo?.phoneNum);
}
