<script setup>
import { myPageApi } from "@/api";
import BalanceList from "@/components/balance/balance-list.vue";
import { useI18n } from "vue-i18n";
import { getDisplayName, isAutogeneratedNickname } from "@/utils/user";

const router = useRouter();
const { t } = useI18n();

// Obtener info del usuario
const { data: userInfo, error } = myPageApi.myInfo();

// Nombre a mostrar: si el nickname es real (usuario lo editó) va tal cual,
// si es el autogenerado tipo "b9xN3842" cae a "Hola, ···1234". Mismo criterio
// que en mine-page.vue (ver utils/user.js).
const hasRealName = computed(() => {
  const nick = userInfo.value?.nickName?.trim();
  return !!nick && !isAutogeneratedNickname(nick);
});
const displayName = computed(() =>
  getDisplayName(userInfo.value) || t("routes.mine.defaultUser")
);
const headerName = computed(() =>
  hasRealName.value
    ? displayName.value
    : t("routes.mine.greeting", { name: displayName.value })
);

// Ir a recargar
const handleTopUp = () => {
  router.push("/wallet/top-up");
};
</script>

<template>
  <div class="wallet-page">
    <!-- Header oscuro con info de usuario -->
    <div class="wallet-header">
      <div class="wallet-header__bg"></div>
      <div class="wallet-header__content">
        <div class="wallet-avatar">
          <van-icon name="user-o" size="28" color="#00BBFC" />
        </div>
        <div class="wallet-user-info">
          <h2 class="wallet-user-name">{{ headerName }}</h2>
          <p class="wallet-user-phone">{{ userInfo?.phoneNum || '' }}</p>
        </div>
      </div>
    </div>

    <!-- Balance Card flotante -->
    <div class="wallet-balance-section">
      <div class="wallet-balance-card">
        <div class="wallet-balance-card__top">
          <span class="wallet-balance-card__label">{{ t('routes.wallet.balance.current') }}</span>
          <div class="wallet-balance-card__amount">
            <span class="wallet-balance-card__currency">$</span>
            <price-tag :price="userInfo?.balance" :show-currency="false" />
          </div>
        </div>
        <van-button
          round
          block
          class="wallet-topup-btn"
          @click="handleTopUp"
        >
          {{ t('routes.wallet.action.topUp') }}
        </van-button>
      </div>
    </div>

    <!-- Historial de movimientos -->
    <div class="wallet-transactions">
      <div class="wallet-transactions__header">
        <h3 class="wallet-transactions__title">{{ t('routes.wallet.balance.record') }}</h3>
        <router-link to="/wallet/balance" class="wallet-transactions__link">
          {{ t('routes.wallet.balance.viewMore') }}
          <van-icon name="arrow" size="12" />
        </router-link>
      </div>
      <balance-list />
    </div>
  </div>
</template>

<style scoped>
.wallet-page {
  min-height: 100vh;
  background: var(--background-color);
}

/* Header */
.wallet-header {
  position: relative;
  padding: 24px 20px 50px;
  overflow: hidden;
}

.wallet-header__bg {
  position: absolute;
  inset: 0;
  background:
    radial-gradient(120% 90% at 100% 0%, rgba(0, 187, 252, 0.16) 0%, transparent 55%),
    linear-gradient(160deg, #0B0B0D 0%, #000000 100%);
}

.wallet-header__content {
  position: relative;
  z-index: 1;
  display: flex;
  align-items: center;
  gap: 14px;
}

.wallet-avatar {
  width: 56px;
  height: 56px;
  border-radius: 50%;
  background: rgba(255, 255, 255, 0.12);
  border: 2px solid rgba(0, 187, 252, 0.3);
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
}

.wallet-user-info {
  flex: 1;
  min-width: 0;
}

.wallet-user-name {
  font-size: 18px;
  font-weight: 700;
  color: #fff;
  margin: 0 0 2px;
}

.wallet-user-phone {
  font-size: 13px;
  color: rgba(255, 255, 255, 0.5);
  margin: 0;
}

/* Balance Card */
.wallet-balance-section {
  padding: 0 16px;
  margin-top: -30px;
  position: relative;
  z-index: 2;
}

.wallet-balance-card {
  background: var(--surface-color);
  border: 1px solid var(--line-color);
  border-radius: 16px;
  padding: 24px 20px;
  box-shadow: 0 12px 30px -18px rgba(0, 0, 0, 0.85);
}

.wallet-balance-card__top {
  text-align: center;
  margin-bottom: 20px;
}

.wallet-balance-card__label {
  font-size: 13px;
  color: var(--text-secondary);
  display: block;
  margin-bottom: 8px;
}

.wallet-balance-card__amount {
  display: flex;
  align-items: baseline;
  justify-content: center;
  font-size: 40px;
  font-weight: 800;
  color: var(--text-primary);
}

.wallet-balance-card__currency {
  font-size: 20px;
  font-weight: 600;
  margin-right: 2px;
  color: var(--text-secondary);
}

.wallet-topup-btn {
  background: linear-gradient(135deg, #00BBFC 0%, #0090CC 100%) !important;
  color: #fff !important;
  border: none !important;
  font-size: 15px;
  font-weight: 700;
  height: 44px;
  letter-spacing: 0.3px;
}

/* Transactions */
.wallet-transactions {
  padding: 0 16px;
  margin-top: 20px;
}

.wallet-transactions__header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 12px;
}

.wallet-transactions__title {
  font-size: 16px;
  font-weight: 700;
  color: var(--text-primary);
  margin: 0;
}

.wallet-transactions__link {
  display: flex;
  align-items: center;
  gap: 2px;
  font-size: 13px;
  color: #00BBFC;
  text-decoration: none;
  font-weight: 500;
}
</style>
